######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 29 18:04:51 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += std_lib_facilities.h
SOURCES += qt_gui.cpp
