######################################################################
# Automatically generated by qmake (2.01a) Do. Dez 29 16:47:07 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qt_gui.cpp
