######################################################################
# Automatically generated by qmake (2.01a) Mon Jul 30 13:19:07 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += Notepad.cpp
